### ISSUE TITLE
Help menu redesign

### ISSUE THREAD

**Issue by AlexFlipnote** [BeardDesign1/Material-design-theme#11]
So I noticed that the help menu looks like this
<img src="https://i.mify.pw/3896d7.png" width="50%">

So I changed it to this:
<img src="https://i.mify.pw/9d251e.png" width="50%"><br>
<img src="https://i.mify.pw/cbb058.png" width="50%">

Hope you like the changes, here is the source code that I have on my dev version:
```css
.need-help-modal .header input[type=text] {
  box-shadow: 0 0;
  border-radius: 0;
  border-bottom: 2px solid #696969;
}

.need-help-modal .header input[type=text]:focus {
  border-bottom: 2px solid #696969;
}

.need-help-modal .footer {
  background-color: #212121;
  color: white;
}

.need-help-modal .header {
  background-color: #212121;
  color: #212121;
}

.need-help-modal .form-inner .failed .poop {
  background-image: url(/assets/4dc13fd52f691020a1308c5b6cbc6f49.svg);
}

.need-help-modal .form-inner .failed p {
  display: none;
}

.need-help-modal .form-inner .failed:after {
  content: 'Looks like the help site is down...';
  color: white;
}
```
