### ISSUE TITLE
Dark theme button with colour

### ISSUE THREAD

**Issue by AlexFlipnote** [BeardDesign1/Material-design-theme#12]
I have noticed that the button is untouched when you enable dark theme, so I added some colours to see the difference, might as well send it here
```css
.radio-theme.dark.compact label, .radio-theme.dark label {
    background: #e74c3c;
}

.radio-theme input[type=radio]:checked~label {
    background: #27ae60;
}
```
<img src="https://i.mify.pw/07a3ca.gif">
