### ISSUE TITLE
Missing icon for Nitro in user-settings-modal

### ISSUE THREAD

**Issue by AlexFlipnote** [BeardDesign1/Material-design-theme#8]
This is at **Line 1678**
I solved by adding this: 
```css
.user-settings-modal .tab-bar.SIDE .tab-bar-item:nth-of-type(3):before {
    content: url(https://storage.googleapis.com/material-icons/external-assets/v4/icons/svg/ic_favorite_white_24px.svg);
}
```
<img src="https://i.mify.pw/2de063.png">
